### ISSUE TITLE
Health system

### ISSUE THREAD

**Issue by ShmelJUJ** [GeorgeD615/PrototypeX#12]
**Смерть после попадания нескольких пуль**

После того, как у противника кончается здоровье, тот умирает. На месте смерти остаётся модель мёртвого противника. 

При смерти игрока, вся игра начинается заново с уровнем сложности -1 от того, на который был оценён игрок при последнем прохождении уровня. (Это реализуется вместе с адаптивной сложностью)

**Comment by GeorgeD615** [comment]
Implemented
