### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by ShmelJUJ** [GeorgeD615/PrototypeX#13]
**Искусственный интеллект противников**

При попадании игрока в область зрения противника, противник начинает быстро приближаться к игроку, пока не окажется на определённом расстоянии от игрока. Если игрок подходит слишком близко, то противник отдаляется на некоторое расстояние, чтобы сохранять дистанцию от игрока. 

При потере игрока из поля зрения противник двигается по кратчайшему пути к игроку.

Противник всё время атакует игрока, пока тот оказывается в поле зрения.

**Comment by GeorgeD615** [comment]
Implemented
